### ISSUE TITLE
Pardus Sürümünü Yükseltmek

### ISSUE THREAD

**Issue by neondev27** [dogukanoksuz/PardusWSL#1]
Merhaba,

Acaba Pardus sürümünü şu anki sürüme yükseltebilir misiniz?

**Comment by dogukanoksuz** [comment]
install.tar.gz dosyasını güncel bir Pardusun root kısmını sıkıştırarak (tar cvzf install.tar.gz /) değiştirin.

**Comment by neondev27** [comment]
Neyse, bari güncellemeleri için Pardus sunucu yükseltme rehberini koyalım da sıkıntı olmasın.
